import { FILE_MODE } from "./install-paths";
import type { FileSystemPort } from "./ports";

/**
 * Environment variables that describe the interactive shell or terminal session
 * rather than durable daemon configuration: shell directory/level markers,
 * Apple launch/XPC context, terminal and multiplexer state, and X11/Wayland
 * session/window state. Keep named entries explicit for traceability; the
 * documented `__*` and `XDG_SESSION_*` families are handled by prefix checks.
 */
const EPHEMERAL_KEYS = new Set([
  "PWD",
  "OLDPWD",
  "SHLVL",
  "_",
  "LaunchInstanceID",
  "XPC_SERVICE_NAME",
  "SECURITYSESSIONID",
  "TERM_PROGRAM_VERSION",
  "TERM_SESSION_ID",
  "ITERM_SESSION_ID",
  "TMUX",
  "STY",
  "DISPLAY",
  "XAUTHORITY",
  "XDG_RUNTIME_DIR",
  "WINDOWID",
  "WINDOWPATH",
]);
const ENV_KEY = /^[A-Za-z_][A-Za-z0-9_]*$/;
const EPHEMERAL_KEY_PREFIXES = ["__", "XDG_SESSION_"] as const;

export class LoginEnvCaptureError extends Error {
  override readonly name = "LoginEnvCaptureError";
  constructor(message: string, readonly reason: unknown) {
    super(message);
  }
}

export async function captureLoginEnv(opts: { shell?: string; cwd?: string } = {}): Promise<Record<string, string>> {
  const shell = opts.shell ?? "/bin/zsh";
  try {
    const process = Bun.spawn({
      cmd: [shell, "-ilc", "env -0"],
      ...(opts.cwd ? { cwd: opts.cwd } : {}),
      stdout: "pipe",
      stderr: "pipe",
    });
    const [exitCode, stdout, stderr] = await Promise.all([
      process.exited,
      new Response(process.stdout).text(),
      new Response(process.stderr).text(),
    ]);
    if (exitCode !== 0) {
      throw new Error(`${shell} exited with ${exitCode}${stderr.trim() ? `: ${stderr.trim()}` : ""}`);
    }
    return parseLoginEnv(stdout);
  } catch (error) {
    if (error instanceof LoginEnvCaptureError) throw error;
    throw new LoginEnvCaptureError("failed to capture login-shell environment", error);
  }
}

export function writeCapturedEnv(filePath: string, env: Record<string, string>, fs: FileSystemPort): void {
  const lines = [
    "# owner-only environment captured from the owner's login shell",
    "# regenerated by pi-mob setup; do not add credentials manually",
    ...Object.keys(env).sort().map((key) => `${key}=${env[key]}`),
  ];
  fs.writeFile(filePath, `${lines.join("\n")}\n`, FILE_MODE);
  fs.chmod(filePath, FILE_MODE);
}

function parseLoginEnv(output: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const record of output.split("\0")) {
    if (record.length === 0) continue;
    const separator = record.indexOf("=");
    if (separator < 1) throw new LoginEnvCaptureError("invalid login-shell environment record", record);
    const key = record.slice(0, separator).trim();
    const value = record.slice(separator + 1);
    if (!ENV_KEY.test(key)) throw new LoginEnvCaptureError("invalid login-shell environment key", key);
    if (value.includes("\n") || value.includes("\0")) {
      throw new LoginEnvCaptureError("invalid login-shell environment value", key);
    }
    if (value.length > 0 && !isEphemeralKey(key)) env[key] = value;
  }
  return env;
}

function isEphemeralKey(key: string): boolean {
  return EPHEMERAL_KEYS.has(key) || EPHEMERAL_KEY_PREFIXES.some((prefix) => key.startsWith(prefix));
}
